"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var attributes_1 = require("./dist/attributes");
exports.controller = attributes_1.controller;
exports.action = attributes_1.action;
exports.routeData = attributes_1.routeData;
exports.request = attributes_1.request;
exports.response = attributes_1.response;
exports.requestHeaders = attributes_1.requestHeaders;
exports.context = attributes_1.context;
